version: '3.3'

services:

  zammad-proxy:
    image: cybergatelabs/letsencrypt
    container_name: zammad-proxy
    hostname: zammad-proxy
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${URL}
      - SUBDOMAINS=${SUBDOMAINS},
      - EXTRA_DOMAINS=${EXTRA_DOMAINS}
      - VALIDATION=${VALIDATION}
      - EMAIL=${EMAIL}
      - DHLEVEL=${DHLEVEL}
      - ONLY_SUBDOMAINS=${ONLY_SUBDOMAINS}
      - STAGING=${STAGING}
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./data/letsencrypt/config:/config
    networks:
     - zammad-network
     
  zammad-elasticsearch:
    image: ${IMAGE_REPO}:zammad-elasticsearch
    container_name: zammad-elasticsearch
    hostname: zammad-elasticsearch
    labels:
      - "io.rancher.container.pull_image: always"
      - "traefik.enable=false"
    restart: always
    volumes:
      - zammad-elasticsearch:/usr/share/elasticsearch/data
    networks:
     - zammad-network

  zammad-memcached:
    command: ["zammad-memcached"]
    image: ${IMAGE_REPO}:zammad-memcached
    container_name: zammad-memcached
    hostname: zammad-memcached
    labels:
      io.rancher.container.pull_image: always
    restart: always
    networks:
     - zammad-network

  zammad-mariadb:
    image: osixia/mariadb:10.2.8
    container_name: zammad-mariadb
    hostname: zammad-mariadb
    labels:
      - "io.rancher.container.pull_image: always"
      - "traefik.enable=false"
    restart: always
    environment:
      MARIADB_ROOT_ALLOWED_NETWORKS: "#PYTHON2BASH:['localhost','127.0.0.1','::1', '172.%.%.%']"
      MARIADB_DATABASES: "zammad"
      MARIADB_USERS: "#PYTHON2BASH:[{'zammad': 'zammad'}]"
    volumes:
      - zammad-mariadb:/var/lib/mysql
    networks:
     - zammad-network

  zammad-zammad:
    image: osixia/zammad:3.2.0
    container_name: zammad-zammad
    hostname: zammad-zammad
    command: -l info
    labels:
      - "io.rancher.container.pull_image: always"
      - "traefik.protocol=https"
      - "traefik.frontend.rule=Host:zammad.example.org;PathPrefix:/"
      - "traefik.port=443"
    links:
      - zammad-elasticsearch
      - zammad-mariadb
      - zammad-memcached
    ports:
      - "6443:443"
    restart: always
    environment:
      ZAMMAD_DB_HOST: "zammad-mariadb"
      ZAMMAD_DB_NAME: "zammad"
      ZAMMAD_DB_USER: "zammad"
      ZAMMAD_DB_PASSWORD: ${ZAMMAD_DB_PASSWORD}
      ZAMMAD_ELASTICSEARCH_URL: "http://zammad-elasticsearch:9200"
      ZAMMAD_MEMCACHED_HOST: zammad-memcached
    volumes:
      - zammad-backup:/data/backup
    networks:
      - zammad-network

volumes:
  zammad-elasticsearch:
    driver: local
  zammad-mariadb:
    driver: local
  zammad-backup:
    driver: local

networks:
  zammad-network:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: br-zammad
    ipam:
      driver: default
      config:
        - subnet: 172.26.1.0/24
